version: '3'

services:
  speedtest:
    build:
      context: .
      dockerfile: Dockerfile
    image: infobits-speedtest:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: ["-port", "8080"]